In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/0.MKCE/14.Neural  Network/mnist_train.csv")

In [ ]:
data

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to 28x28
dtypes: int64(785)
memory usage: 359.3 MB


In [ ]:
data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

In [ ]:
x = data.drop(['label'],axis=1)
y = data['label']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.25,random_state=0)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(45000, 784)
(15000, 784)
(45000,)
(15000,)


In [ ]:
model = Perceptron()

In [ ]:
model.fit(x_train,y_train)

Perceptron()

In [ ]:
pre = model.predict(x_test)
model.predict(x_test)

array([3, 6, 6, ..., 9, 0, 2])

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
accuracy_score(y_test,pre)

0.8786666666666667

In [ ]:
confusion_matrix(y_test,pre)

array([[1484,    0,    0,    1,    2,    6,   10,    1,    6,    0],
       [   0, 1688,    2,   17,    6,    2,    1,    2,    9,    1],
       [  32,   39, 1115,  120,   22,    7,   40,   27,   48,    8],
       [  17,    5,   10, 1413,    8,   25,   10,   22,   17,   21],
       [   5,    3,    4,    3, 1340,    5,   17,    2,    9,   46],
       [  41,    8,    3,  107,   41,  988,   34,    9,   84,   27],
       [  21,    6,    4,    2,   14,   17, 1386,    2,   16,    0],
       [   5,    7,    8,   12,   22,    4,    0, 1395,    9,   73],
       [  39,   53,    4,   86,   59,   55,   11,   10, 1134,   33],
       [  18,   11,    2,   26,  137,    6,    0,   53,    3, 1237]])

In [ ]:
z=classification_report(y_test,pre)
print(z)

              precision    recall  f1-score   support

           0       0.89      0.98      0.94      1510
           1       0.93      0.98      0.95      1728
           2       0.97      0.76      0.85      1458
           3       0.79      0.91      0.85      1548
           4       0.81      0.93      0.87      1434
           5       0.89      0.74      0.80      1342
           6       0.92      0.94      0.93      1468
           7       0.92      0.91      0.91      1535
           8       0.85      0.76      0.80      1484
           9       0.86      0.83      0.84      1493

    accuracy                           0.88     15000
   macro avg       0.88      0.88      0.88     15000
weighted avg       0.88      0.88      0.88     15000



In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
p = model.predict(x_test)
model.predict(x_test)

array([3, 6, 6, ..., 9, 7, 2])

In [ ]:
accuracy_score(y_test,p)

0.9194666666666667

In [ ]:
confusion_matrix(y_test,p)

array([[1469,    0,    5,    1,    3,   14,   10,    2,    4,    2],
       [   0, 1692,    9,    7,    1,    5,    0,    3,    9,    2],
       [   6,   10, 1297,   37,   16,    8,   18,   18,   39,    9],
       [   7,    7,   34, 1379,    2,   50,    5,   13,   39,   12],
       [   2,    5,    8,    1, 1327,    5,   19,    6,    6,   55],
       [  17,    4,   12,   51,   16, 1137,   25,    9,   54,   17],
       [   9,    2,   17,    0,   11,   17, 1402,    3,    7,    0],
       [   2,    6,   19,    8,   12,    2,    0, 1424,    7,   55],
       [   7,   33,   22,   30,    6,   49,   10,    3, 1302,   22],
       [   6,    7,    3,   13,   46,   10,    0,   35,   10, 1363]])

In [ ]:
s = classification_report(y_test,p)
print(s)

              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1510
           1       0.96      0.98      0.97      1728
           2       0.91      0.89      0.90      1458
           3       0.90      0.89      0.90      1548
           4       0.92      0.93      0.92      1434
           5       0.88      0.85      0.86      1342
           6       0.94      0.96      0.95      1468
           7       0.94      0.93      0.93      1535
           8       0.88      0.88      0.88      1484
           9       0.89      0.91      0.90      1493

    accuracy                           0.92     15000
   macro avg       0.92      0.92      0.92     15000
weighted avg       0.92      0.92      0.92     15000

